#!/usr/bin/env bash
# demo_mapping.sh — Build tenancies_v1.demo.json for Terraform to upload to the bucket.
#
# In demo mode (GDIR_DEMO_MODE=true): auto-discovers the real tenancy key and maps
# synthetic template data to it, writing tenancies_v1.demo.json. All clients (Shell,
# Node.js, Terraform) then read the synthetic data transparently from the bucket.
#
# In normal mode: copies tenancies_v1.json to tenancies_v1.demo.json unchanged.
#
# tenancies_v1.demo.json is NOT tracked by git — it is either generated by this script
# (demo mode) or supplied externally by the data owner (production).
#
# Usage (demo mode — live OCI connection, tenancy key auto-discovered):
#   GDIR_DEMO_MODE=true bash manager/demo_mapping.sh
#
# Usage (demo mode — offline, explicit tenancy and region keys):
#   GDIR_DEMO_MODE=true TENANCY_KEY=my_corp REGION_KEY=eu-zurich-1 bash manager/demo_mapping.sh
#
# Usage (normal mode — copies static tenancies_v1.json):
#   bash manager/demo_mapping.sh
#
# After running, upload to the bucket:
#   cd manager && terraform apply
#
# Environment Variables:
#   GDIR_DEMO_MODE    "true" to enable demo mapping (default: copies static data).
#   GDIR_DEMO_TENANT  Synthetic template tenant key to use as source (default: acme_prod).
#   TENANCY_KEY       Optional: override real tenancy key discovery.
#   REGION_KEY        Optional: override real region key discovery.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_FILE="$SCRIPT_DIR/tenancies_v1.json"
OUTPUT_FILE="$SCRIPT_DIR/tenancies_v1.demo.json"
GDIR_DEMO_TENANT="${GDIR_DEMO_TENANT:-acme_prod}"

if [[ "${GDIR_DEMO_MODE:-}" == "true" ]]; then

  # --- Discover real tenancy key (no catalog validation — may not be onboarded yet) ---
  if [[ -n "${TENANCY_KEY:-}" ]]; then
    real_tenancy_key="$TENANCY_KEY"
  else
    _ocid="$(oci os ns get-metadata --query 'data."default-s3-compartment-id"' --raw-output)"
    real_tenancy_key="$(oci iam tenancy get --tenancy-id "$_ocid" --query 'data.name' --raw-output)"
  fi

  # --- Discover real region key (from bucket OCID or override) ---
  # The client auto-discovers the region from the bucket OCID; the live.json must use
  # the same region key so data lookups succeed.
  if [[ -n "${REGION_KEY:-}" ]]; then
    real_region_key="$REGION_KEY"
  else
    _bucket_ocid="$(oci os bucket get --bucket-name "${GDIR_BUCKET:-gdir_info}" \
      --query 'data.id' --raw-output)"
    real_region_key="$(echo "$_bucket_ocid" | awk -F'.' '{print $4}')"
  fi

  # --- Extract template tenant data from static source ---
  template_data="$(jq --arg t "$GDIR_DEMO_TENANT" '.[$t]' "$SOURCE_FILE")"
  if [[ "$template_data" == "null" || -z "$template_data" ]]; then
    echo "ERROR: Template tenant '$GDIR_DEMO_TENANT' not found in $SOURCE_FILE" >&2
    exit 1
  fi

  # --- Remap template region → real region key ---
  # Pick the first template region's data and store it under the real region key.
  # This ensures the client's auto-discovered region key resolves to valid data.
  _tmpl_region="$(echo "$template_data" | jq -r '.regions | keys[0]')"
  _tmpl_region_data="$(echo "$template_data" | jq --arg r "$_tmpl_region" '.regions[$r]')"
  _realm="$(echo "$template_data" | jq -r '.realm')"

  # --- Build live.json: real tenancy key + real region key → template region data ---
  schema_version="$(jq -r '.schema_version' "$SOURCE_FILE")"
  demo_corp_data="$(jq '.demo_corp // null' "$SOURCE_FILE")"

  jq -n \
    --arg sv         "$schema_version" \
    --arg tenant_key "$real_tenancy_key" \
    --arg realm      "$_realm" \
    --arg region_key "$real_region_key" \
    --argjson region_data "$_tmpl_region_data" \
    --argjson demo_corp "$demo_corp_data" \
    '{
      schema_version: $sv,
      ($tenant_key): {
        realm:   $realm,
        regions: { ($region_key): $region_data }
      }
    }
    + (
      if ($tenant_key != "demo_corp" and $demo_corp != null)
      then { "demo_corp": $demo_corp }
      else {}
      end
    )' > "$OUTPUT_FILE"

  echo "=== Demo Mode — Tenancy Data Mapping ==="
  echo "Real tenancy key  : $real_tenancy_key"
  echo "Real region key   : $real_region_key"
  echo "Template tenant   : $GDIR_DEMO_TENANT (region: $_tmpl_region)"
  echo "Mapped realm      : $_realm"
  if [[ "$demo_corp_data" != "null" && "$real_tenancy_key" != "demo_corp" ]]; then
    echo "Retained tenant   : demo_corp"
  fi
  echo "Output file       : $OUTPUT_FILE"
  echo ""
  echo "NOTICE: Synthetic data only. Not for production use."
  echo "Next step: cd manager && terraform apply"

else

  # --- Normal mode: use static source as-is ---
  cp "$SOURCE_FILE" "$OUTPUT_FILE"
  echo "Copied tenancies_v1.json → tenancies_v1.demo.json"
  echo "Next step: cd manager && terraform apply"

fi
