output "last_updated_timestamp" { value = local.last_updated_timestamp }
output "schema_version"         { value = local.schema_version }
output "tenancies"              { value = local.tenancies }
output "tenancy"                { value = local.tenancy }
output "tenancy_realm"          { value = local.realm }
output "tenancy_region"         { value = local.tenancy_region }
output "tenancy_region_keys"    { value = local.tenancy_region_keys }
output "tenancy_region_network" { value = local.tenancy_region_network }
output "tenancy_region_cidr_private" { value = local.tenancy_region_cidr_private }
output "tenancy_region_cidr_by_tag"  { value = local.tenancy_region_cidr_by_tag }
output "tenancy_region_proxy"        { value = local.tenancy_region_proxy }
output "tenancy_region_proxy_url"    { value = try(local.tenancy_region_proxy.url, null) }
output "tenancy_region_proxy_ip"     { value = try(local.tenancy_region_proxy.ip, null) }
output "tenancy_region_proxy_port"   { value = try(local.tenancy_region_proxy.port, null) }
output "tenancy_region_proxy_noproxy" { value = local.tenancy_region_proxy_noproxy }
output "tenancy_region_proxy_noproxy_string" { value = local.tenancy_region_proxy_noproxy_string }
output "tenancy_region_vault"        { value = local.tenancy_region_vault }
output "tenancy_region_vault_ocid"   { value = try(local.tenancy_region_vault.ocid, null) }
output "tenancy_region_vault_crypto_endpoint" { value = try(local.tenancy_region_vault.crypto_endpoint, null) }
output "tenancy_region_vault_management_endpoint" { value = try(local.tenancy_region_vault.management_endpoint, null) }
output "tenancy_region_github"       { value = local.tenancy_region_github }
output "tenancy_region_github_runner" { value = local.tenancy_region_github_runner }
output "tenancy_region_github_runner_labels" { value = local.tenancy_region_github_runner_labels }
output "tenancy_region_github_runner_image" { value = local.tenancy_region_github_runner_image }
output "tenancy_region_observability" { value = local.tenancy_region_observability }
output "tenancy_region_prometheus_scraping_cidr" { value = local.tenancy_region_prometheus_scraping_cidr }
output "tenancy_region_loki_destination_cidr" { value = local.tenancy_region_loki_destination_cidr }
output "tenancy_region_loki_fqdn" { value = local.tenancy_region_loki_fqdn }
