# tenancies_v1.demo.json is the working copy built by demo_mapping.sh.
# It is NOT tracked by git — generated by demo_mapping.sh (demo mode) or
# supplied externally by the data owner (production).
# Falls back to tenancies_v1.json if the demo file has not been generated yet.
locals {
  tenancies_data_file = fileexists("${path.module}/tenancies_v1.demo.json") ? "${path.module}/tenancies_v1.demo.json" : "${path.module}/tenancies_v1.json"
}

# Validate the active tenancies data file against the schema before uploading.
data "external" "validate_tenancies_v1" {
  program = ["bash", "${path.module}/validate.sh"]
  query = {
    schema_file = "${path.module}/tenancies_v1.schema.json"
    data_file   = local.tenancies_data_file
  }
}

resource "oci_objectstorage_object" "v1_tenancies" {
  bucket       = oci_objectstorage_bucket.info.name
  namespace    = data.oci_objectstorage_namespace.ns.namespace
  object       = "tenancies/v1"
  content      = jsonencode(merge(jsondecode(file(local.tenancies_data_file)), { last_updated_timestamp = timestamp() }))
  content_type = "application/json"

  depends_on = [data.external.validate_tenancies_v1]
}

output "tenancies_v1_object_name" {
  description = "Object path for tenancies/v1 data in the bucket"
  value       = oci_objectstorage_object.v1_tenancies.object
}
